### ISSUE TITLE
Wrong URL in Readme?

### ISSUE THREAD

**Issue by lurch** [PedalPi/PedalPi-Raspberry#1]
The readme currently says `git clone --recursive https://github.com/PedalPi/WebService` - should it instead be the URL of **this** repo i.e. `https://github.com/PedalPi/PedalPi-Raspberry` ?

**Comment by SrMouraSilva** [comment]
Yes! The current Readme isn't updated :/

An observation, for real tests in raspberry, it's neccessary uncomment the line:
https://github.com/PedalPi/PedalPi-Raspberry/blob/master/start.py#L16

**Comment by lurch** [comment]
I haven't tried running any of your code, I just happened to spot what looked like an error while clicking around your different repos... ;)  (out of curiosity)
